export const REQUEST_GET_POSTS = 'REQUEST_GET_POSTS';
export const SUCCESS_GET_POSTS = 'SUCCESS_GET_POSTS';
export const FAILURE_GET_POSTS = 'FAILURE_GET_POSTS';

export const REQUEST_CREATE_POST = 'REQUEST_CREATE_POST';
export const SUCCESS_CREATE_POST = 'SUCCESS_CREATE_POST';
export const FAILURE_CREATE_POST = 'FAILURE_CREATE_POST';

export const REQUEST_GET_POST = 'REQUEST_GET_POST';
export const SUCCESS_GET_POST = 'SUCCESS_GET_POST';
export const FAILURE_GET_POST = 'FAILURE_GET_POST';

export const REQUEST_UPDATE_POST = 'REQUEST_UPDATE_POST';
export const SUCCESS_UPDATE_POST = 'SUCCESS_UPDATE_POST';
export const FAILURE_UPDATE_POST = 'FAILURE_UPDATE_POST';

export const REQUEST_DELETE_POST = 'REQUEST_DELETE_POST';
export const SUCCESS_DELETE_POST = 'SUCCESS_DELETE_POST';
export const FAILURE_DELETE_POST = 'FAILURE_DELETE_POST';
